#! /bin/bash

#CONSTANTS
INIPATH=/etc/adtn/adtn.ini
DATAPATH=/var/lib/adtn
USER=adtn
PIDPATH=/var/run/adtn
MAINSRVC=adtnplatform
SERVICES="adtnplatform.conf"
#END_CONSTANTS

#COMMON_FUNCTIONS
if [ "$(whoami)" != "root" ]; then
  echo "This script must be executed as sudo, exiting..."
  exit 1;
fi
#END_COMMON_FUNCTIONS
