#! /bin/bash

if [ "$(whoami)" != "root" ]; then
  echo "This script must be executed as sudo, exiting..."
  exit 1;
fi

chown adtn:adtn /usr/bin/adtn-ping
chmod u+s /usr/bin/adtn-ping
chown adtn:adtn /usr/bin/adtn-traceroute
chmod u+s /usr/bin/adtn-traceroute
chown adtn:adtn /usr/bin/adtn-neighbours
chmod u+s /usr/bin/adtn-neighbours
chown adtn:adtn /usr/bin/adtn-sender
chmod u+s /usr/bin/adtn-sender

exit 0;
